---
- name: Install web stack (generic)
  hosts: webservers
  become: true
  gather_facts: true

  tasks:
    - name: Ensure python3 is present
      package:
        name: python3
        state: present

